### PR TITLE
Added the ability to change initial displayed statistic

### PR DESCRIPTION
**Pull request by siguroot**
Hi there, first off I'd like to say I love this application so much.  I have been using it for years, all the way back to the perl version.  The ability to change the initial statistic displayed would be very valuable to me.  I am not a great programmer, so I have 0 ego as to the solution for this.   Maintaining my own fork perhaps is the solution.  Your call.

### CODE REVIEW

**Comment by famzah** [comment]
Hi, I'm glad that "ping-multi" is useful for you, too! I will try to come up with a new version this week and let you test it before I release it at PyPi.

**Comment by famzah** [comment]
@siguroot, thank you for the idea and the contribution. I've merged your code with slight modifications.

Please test if the new feature functions as expected for you. You need to checkout "ping-multi" from GitHub directly because I haven't published the new version to PyPi, yet:
```bash
git clone https://github.com/famzah/ping-multi-ext.git
python3 -m venv ping-multi-ext
cd ping-multi-ext/
. bin/activate
pip3 install blessings curtsies
./ping-multi
```

**Comment by siguroot** [comment]
It worked great in test!  Yes, you did more less what I did but much more elegantly.  Very good learning experience.

**Comment by famzah** [comment]
Released at PyPi.

You can upgrade using ``pip install --upgrade ping-multi-ext``

**Pull request closed without merging**
